-- Les histoires toutes écrites de la bibliothèque.
-- {enfant} est remplacé par le prénom réglé dans le plugin (ou « mon trésor »),
-- {doudou} par « ton doudou » suivi de son nom s'il est réglé.
return {
    histoires = {
        {
            id = "petite_etoile",
            titre = "La petite étoile qui ne voulait pas dormir",
            age_min = 3, age_max = 5, themes = { "coucher" },
            paragraphes = {
                "Tout là-haut dans le ciel, il y avait une petite étoile qui s'appelait Lumina.",
                "Chaque matin, quand le soleil se levait, toutes les étoiles allaient se coucher. Mais Lumina, elle, ne voulait jamais dormir.",
                "« Je veux voir le jour ! disait-elle. Je veux voir les enfants jouer, les fleurs s'ouvrir et les oiseaux chanter ! »",
                "Un matin, Lumina décida de rester éveillée. Elle se cacha derrière un petit nuage et attendit.",
                "Le soleil arriva, grand et chaud. Il brillait si fort que Lumina devint presque invisible. Personne ne pouvait la voir !",
                "« Coucou ! cria Lumina. Je suis là ! » Mais personne ne l'entendait. Les enfants jouaient sans lever les yeux. Lumina se sentit toute petite et toute seule.",
                "Le soleil la vit et lui dit doucement : « Tu sais, petite étoile, le jour, c'est mon tour de briller. Et la nuit, c'est le tien. Ce soir, des enfants vont regarder le ciel pour te dire bonne nuit. »",
                "Alors Lumina bâilla, un tout petit bâillement d'étoile. Elle se blottit dans son nuage et s'endormit.",
                "Le soir venu, elle se réveilla et brilla plus fort que jamais. Et en bas, à sa fenêtre, un enfant leva les yeux et murmura : « Bonne nuit, petite étoile. »",
                "Bonne nuit, {enfant}. Ce soir, Lumina brille rien que pour toi.",
            },
        },
        {
            id = "escargot_presse",
            titre = "Monsieur Escargot est pressé",
            age_min = 3, age_max = 5, themes = { "humour", "patience" },
            paragraphes = {
                "Ce matin, Monsieur Escargot ouvre un œil. Puis l'autre. « Oh là là ! Je suis en retard ! »",
                "Aujourd'hui, c'est la fête de Madame Tortue, de l'autre côté du jardin. Et la fête commence à midi !",
                "Monsieur Escargot sort de sa coquille et se dépêche. Il se dépêche très, très fort. Mais un escargot qui se dépêche, ça avance… tout doucement.",
                "Un papillon passe en volant. « Bonjour, Monsieur Escargot ! Où allez-vous comme ça ? » « À la fête de Madame Tortue ! Je suis pressé ! » Le papillon rit et s'envole.",
                "Une fourmi passe en trottinant. « Bonjour, Monsieur Escargot ! Vous voulez que je vous porte ? » « Merci, mais je suis un peu trop lourd pour toi ! »",
                "Un lapin passe en sautant. Hop, hop, hop ! « Monsieur Escargot, la fête a peut-être déjà commencé ! » Monsieur Escargot soupire et continue d'avancer. Un petit bout. Encore un petit bout.",
                "Enfin, le soleil est tout en haut du ciel. Monsieur Escargot arrive chez Madame Tortue, tout essoufflé. « Pardon, pardon, je suis en retard ! »",
                "Mais il n'y a personne. Pas de Madame Tortue, pas de fête. Monsieur Escargot attend. Il attend. Il attend encore.",
                "Et soudain, Madame Tortue arrive, tout doucement, avec un gâteau posé sur sa carapace. « Bonjour, Monsieur Escargot ! Oh, vous êtes déjà là ? Vous êtes drôlement rapide ! »",
                "Monsieur Escargot devient tout rouge de fierté. Et ce jour-là, pour la première fois de sa vie, il fut le premier arrivé à une fête.",
            },
        },
        {
            id = "colere_petit_ours",
            titre = "La colère de Petit Ours",
            age_min = 3, age_max = 5, themes = { "emotions" },
            paragraphes = {
                "Petit Ours construit une tour avec ses cubes. Un cube, deux cubes, trois cubes… La tour est très haute.",
                "Mais patatras ! La tour tombe. Tous les cubes roulent par terre.",
                "Alors Petit Ours sent quelque chose qui monte dans son ventre. Ça chauffe, ça gronde, ça pique. C'est la colère ! « GRRRRR ! » crie Petit Ours en tapant des pieds.",
                "Maman Ourse arrive. Elle ne gronde pas. Elle s'assoit à côté de lui. « Tu es en colère, mon Petit Ours ? » « OUI ! » rugit Petit Ours.",
                "« La colère, c'est comme un gros orage dans le ventre, dit Maman Ourse. On ne peut pas l'empêcher de venir. Mais on peut l'aider à repartir. Tu veux essayer ? »",
                "« Comment on fait ? » demande Petit Ours en reniflant.",
                "« D'abord, on fait comme si on sentait une fleur : on respire tout doucement par le nez. Ensuite, on souffle sur une bougie : fffffff. »",
                "Petit Ours sent la fleur. Il souffle la bougie. Une fois. Deux fois. Trois fois. Et l'orage dans son ventre devient tout petit, tout petit, comme une petite pluie.",
                "« Ça va mieux », dit Petit Ours. Maman Ourse lui fait un câlin tout chaud. Puis, ensemble, ils reconstruisent la tour, encore plus haute qu'avant.",
                "Et toi, {enfant}, tu veux sentir la fleur et souffler la bougie avec Petit Ours ?",
            },
        },
        {
            id = "chaussette",
            titre = "Qui a vu ma chaussette ?",
            age_min = 2, age_max = 3, themes = { "humour", "coucher" },
            paragraphes = {
                "Bébé Chat a perdu sa chaussette rouge. « Qui a vu ma chaussette ? »",
                "Il demande au chien. « Chien, as-tu vu ma chaussette ? » « Ouaf ! Non, je n'ai vu que mon os. »",
                "Il demande à la poule. « Poule, as-tu vu ma chaussette ? » « Cot-cot ! Non, je n'ai vu que mon œuf. »",
                "Il demande au poisson. « Poisson, as-tu vu ma chaussette ? » « Blop, blop ! Non, je n'ai vu que mes bulles. »",
                "Il demande à la souris. « Souris, as-tu vu ma chaussette ? » La souris ne répond pas. Elle dort… dans une petite chaussette rouge !",
                "« Ma chaussette ! » dit Bébé Chat. « Oh, pardon, dit la souris en bâillant. C'est un si joli lit ! »",
                "Bébé Chat sourit. « Garde-la pour cette nuit. Bonne nuit, petite souris ! » Et Bébé Chat s'endort avec un seul pied tout chaud.",
            },
        },
        {
            id = "petits_canards",
            titre = "Un, deux, trois, petits canards",
            age_min = 2, age_max = 3, themes = { "apprendre", "compter" },
            paragraphes = {
                "Un petit canard se promène au bord de l'étang. Coin !",
                "Il rencontre un autre petit canard. Un, deux. Deux petits canards. Coin, coin !",
                "Ils rencontrent encore un petit canard. Un, deux, trois. Trois petits canards. Coin, coin, coin !",
                "Puis un quatrième ! Un, deux, trois, quatre. Quatre petits canards. Coin, coin, coin, coin !",
                "Et enfin, un cinquième, tout petit, tout petit. Un, deux, trois, quatre, cinq. Cinq petits canards !",
                "Tous ensemble, ils plongent dans l'étang. Plouf, plouf, plouf, plouf, plouf !",
                "Puis Maman Cane appelle : « Les enfants, c'est l'heure du dodo ! » Et les cinq petits canards se blottissent sous ses ailes. Chut… Bonne nuit, les petits canards.",
                "Et toi, {enfant}, tu sais compter jusqu'à cinq sur tes doigts ?",
            },
        },
        {
            id = "bisou_lune",
            titre = "Le bisou de la lune",
            age_min = 2, age_max = 4, themes = { "coucher" },
            paragraphes = {
                "Chaque soir, quand tout le monde est couché, la lune fait le tour du monde.",
                "Elle passe au-dessus des montagnes et fait un bisou aux petites chèvres endormies.",
                "Elle passe au-dessus de la mer et fait un bisou aux petits poissons.",
                "Elle passe au-dessus de la forêt et fait un bisou aux renardeaux, bien au chaud dans leur terrier.",
                "Elle passe au-dessus des maisons et regarde par les fenêtres. Est-ce que tous les enfants sont bien couchés ?",
                "Ce soir, elle s'arrête devant ta fenêtre, {enfant}. Elle te voit dans ton lit, avec {doudou} serré contre toi.",
                "Alors la lune envoie un rayon tout doux, tout argenté, qui glisse jusqu'à ta joue. C'est son bisou.",
                "Ferme les yeux. Tu le sens ? Bonne nuit.",
            },
        },
        {
            id = "nuage_floc",
            titre = "Le nuage qui voulait jouer",
            age_min = 3, age_max = 5, themes = { "emotions", "nature" },
            paragraphes = {
                "Il était une fois un petit nuage tout blanc qui s'appelait Floc. Floc s'ennuyait, tout seul dans le ciel.",
                "Il descendit un peu pour regarder les enfants dans le parc. Ils jouaient au ballon, ils riaient, ils couraient.",
                "« Je veux jouer avec vous ! » cria Floc. Mais quand il s'approcha, il cacha le soleil, et les enfants dirent : « Oh, il fait tout gris ! »",
                "Floc fut si triste qu'il se mit à pleurer. Et quand un nuage pleure… il pleut ! Les enfants coururent se mettre à l'abri.",
                "« Je gâche tout », sanglota Floc. Alors le vent arriva et lui souffla une idée à l'oreille.",
                "Floc sécha ses larmes et se mit à changer de forme. D'abord, il devint un lapin. Puis un éléphant. Puis un bateau avec une grande voile !",
                "En bas, une petite fille leva le doigt : « Regardez ! Le nuage fait un lapin ! » « Non, c'est un éléphant ! » « Un bateau ! » Tous les enfants levaient la tête et riaient.",
                "Floc était si heureux qu'il passa tout l'après-midi à jouer avec eux, en prenant des formes de plus en plus rigolotes.",
                "Et toi, {enfant}, la prochaine fois que tu verras un nuage, regarde bien. C'est peut-être Floc qui veut jouer avec toi.",
            },
        },
        {
            id = "dragon_hoquet",
            titre = "Le dragon qui avait le hoquet",
            age_min = 3, age_max = 5, themes = { "humour", "amitie" },
            paragraphes = {
                "Dans une grotte, tout en haut de la montagne, vivait un petit dragon vert qui s'appelait Hector.",
                "Un matin, Hector se réveilla avec le hoquet. Hic ! Et à chaque hoquet, une petite flamme sortait de son nez. Hic ! Pfff !",
                "« Oh non, dit Hector. Comment je vais faire pour jouer avec mes amis ? Hic ! »",
                "Son amie la chèvre lui dit : « Bois un grand verre d'eau ! » Hector but toute l'eau du ruisseau. Glou, glou, glou. Hic ! Pfff ! Raté.",
                "Son ami le lapin lui dit : « Retiens ta respiration ! » Hector gonfla ses joues, il devint tout rouge… Hic ! Pfff ! Raté.",
                "Son amie la marmotte lui dit : « Mets-toi la tête en bas ! » Hector fit le poirier, les pattes en l'air… Hic ! Pfff ! Raté encore.",
                "Alors une petite souris s'approcha tout doucement derrière lui et cria : « BOU ! »",
                "Hector sursauta si fort qu'il se cogna presque au plafond de la grotte. Puis il attendit. Une seconde. Deux secondes. Trois secondes… Plus de hoquet !",
                "« Merci, petite souris ! » dit Hector. Et pour fêter ça, il fit griller des guimauves pour tous ses amis, avec sa plus belle flamme.",
            },
        },
    },
}
