-- Les trames des histoires inventées. Chaque trame est une histoire à
-- trous : le héros, son compagnon, le lieu et l'objet sont tirés au
-- hasard, et les listes de "choix" ajoutent de la variété.
--
-- Un paragraphe peut être une liste de variantes : une seule est tirée.
-- Règle d'écriture : jamais "de {heros.nom}" ni "que {heros.nom}", car le
-- prénom de l'enfant peut commencer par une voyelle (« de Emma »).

local COINS = {
    { ou = "sous une grande feuille", la = "une coccinelle qui fait la sieste" },
    { ou = "dans un vieux panier", la = "une pelote de laine toute emmêlée" },
    { ou = "derrière un buisson", la = "un escargot qui mange sa salade" },
    { ou = "sous une grosse pierre", la = "une fourmi qui porte une miette" },
    { ou = "dans un trou tout rond", la = "une taupe qui ronfle" },
    { ou = "dans une vieille botte", la = "une chaussette à rayures" },
    { ou = "derrière un pot de fleurs", la = "un papillon qui se repose" },
}

return {
    trames = {
        {
            id = "bonne_nuit",
            titre = { "Bonne nuit, {heros.nom} !", "{heros.nom} dit bonne nuit" },
            age_min = 2, age_max = 4, themes = { "coucher" },
            choix = {
                amis = {
                    { qui = "le hibou", rep = "« Hou-hou, bonne nuit ! » répond le hibou du haut de sa branche." },
                    { qui = "la lune", rep = "La lune fait un grand sourire tout doré." },
                    { qui = "les étoiles", rep = "Les étoiles clignent des yeux : bling, bling, bling." },
                    { qui = "le vent", rep = "Le vent chuchote : « Chut, chut, dors bien. »" },
                    { qui = "la petite grenouille", rep = "« Croâ, croâ, fais de beaux rêves ! » chante la petite grenouille." },
                    { qui = "les fleurs", rep = "Les fleurs referment leurs pétales, tout doucement." },
                    { qui = "le petit escargot", rep = "Le petit escargot rentre dans sa coquille, sans faire de bruit." },
                },
            },
            paragraphes = {
                "Le soleil se couche {lieu.dans}. Le ciel devient tout orange, puis tout rose, puis tout bleu.",
                "{^heros.nom}, {heros.un} {heros.detail}, ouvre grand la bouche et bâille : « Aaaaah ! C'est l'heure de dormir. »",
                "Mais avant de dormir, {heros.nom} veut dire bonne nuit à tout le monde.",
                "« Bonne nuit, {amis#1.qui} ! » {amis#1.rep}",
                "« Bonne nuit, {amis#2.qui} ! » {amis#2.rep}",
                "« Bonne nuit, {amis#3.qui} ! » {amis#3.rep}",
                "« Et bonne nuit, {compagnon.nom} ! » Mais {compagnon.nom}, {compagnon.un} {compagnon.detail}, dort déjà. Rrrr, rrrr, {compagnon|il|elle} ronfle tout doucement.",
                "Tout autour, {lieu.son}. C'est la musique de la nuit.",
                "Alors {heros.nom} se blottit dans {lieu.lit}. {^heros|Il|Elle} ferme un œil… puis l'autre œil…",
                "Bonne nuit, {heros.nom}. Bonne nuit, {lieu.nom}. Et bonne nuit à toi aussi, {enfant}.",
            },
        },
        {
            id = "cache_cache",
            titre = { "Où est {heros.nom} ?", "{heros.nom} joue à cache-cache" },
            age_min = 2, age_max = 4, themes = { "jeu" },
            choix = { coins = COINS },
            paragraphes = {
                "Aujourd'hui, {heros.nom} et {compagnon.nom} jouent à cache-cache {lieu.dans}.",
                "{^compagnon.nom} ferme les yeux et compte : « Un, deux, trois, quatre, cinq ! Attention, j'arrive ! »",
                "Où est {heros.nom} ? {^heros|Est-il|Est-elle} {coins#1.ou} ? Non ! {^coins#1.ou}, il y a seulement {coins#1.la}.",
                "{^heros|Est-il|Est-elle} {coins#2.ou} ? Non ! {^coins#2.ou}, il y a seulement {coins#2.la}.",
                "{^heros|Est-il|Est-elle} {coins#3.ou} ? Non plus ! {^coins#3.ou}, il y a seulement {coins#3.la}.",
                "{^compagnon.nom} réfléchit, réfléchit… Et {lieu.cachette} ?",
                "Oh ! On voit dépasser {heros.depasse}…",
                "« Coucou ! Je t'ai {heros|trouvé|trouvée}, {heros.nom} ! »",
                "{^heros.nom} rit très fort. « À mon tour de chercher ! » Et le jeu recommence, encore et encore, jusqu'à l'heure du goûter.",
            },
        },
        {
            id = "objet_perdu",
            titre = { "{heros.nom} a perdu {objet.son}", "Mais où est {objet.son} ?" },
            age_min = 3, age_max = 5, themes = { "amitie" },
            choix = { coins = COINS },
            paragraphes = {
                "Ce matin, {heros.nom} se réveille de très bonne humeur. Aujourd'hui, {heros|il|elle} a envie de jouer avec {objet.son}.",
                "Mais… où est {objet.son} ? Pas dans {heros.maison}. Pas sous l'oreiller. Pas sous la couverture. {^objet.son} a disparu !",
                "{^heros.nom} a les yeux qui piquent. Une grosse larme roule sur sa joue.",
                "Justement, {compagnon.nom}, {compagnon.un} {compagnon.detail}, passe par là. « Qu'est-ce qui ne va pas ? »",
                "« J'ai perdu {objet.mon}, et je ne {objet|le|la} trouve nulle part ! »",
                "« Ne t'inquiète pas, dit {compagnon.nom}. À deux, on cherche mieux ! »",
                "{^duo|Ils|Elles} regardent {coins#1.ou}. Il y a seulement {coins#1.la}. {^duo|Ils|Elles} regardent {coins#2.ou}. Il y a seulement {coins#2.la}.",
                "Alors {compagnon.nom} a une idée : « Où as-tu joué hier ? » {^heros.nom} réfléchit très fort. « Hier, j'ai joué {lieu.dans}, {lieu.cachette} ! »",
                "{^duo|Ils|Elles} courent jusque là-bas et… « {objet|Le|La} voilà ! » {^objet.son} attendait bien sagement, {lieu.cachette}.",
                "{^heros.nom} fait un énorme câlin à {compagnon.nom}. « Merci ! Tu es {compagnon|un vrai ami|une vraie amie}. »",
                "Et depuis ce jour, quand {heros.nom} a fini de jouer, {heros|il|elle} range toujours {objet.son} au même endroit. Comme ça, plus besoin de chercher !",
            },
        },
        {
            id = "peur_du_noir",
            titre = { "{heros.nom} n'a plus peur du noir", "{heros.nom} et les bruits de la nuit" },
            age_min = 3, age_max = 5, themes = { "coucher", "emotions" },
            choix = {
                ombres = {
                    { peur = "Là-bas, il y a une grande ombre avec des bras tout tordus !", vrai = "C'est un vieil arbre qui fait coucou avec ses branches." },
                    { peur = "Là, deux petits points qui brillent dans le noir !", vrai = "Ce sont deux lucioles qui jouent à chat." },
                    { peur = "J'entends un bruit bizarre : cri-cri, cri-cri !", vrai = "C'est un grillon qui joue de la musique pour la nuit." },
                    { peur = "Par terre, une forme toute ronde qui bouge !", vrai = "C'est un hérisson qui part se promener, tout doucement." },
                    { peur = "J'entends un grand bruit : hou-hou, hou-hou !", vrai = "C'est le hibou qui dit bonsoir à ses voisins." },
                    { peur = "Là-haut, une chose blanche qui flotte !", vrai = "C'est un petit nuage qui passe devant la lune." },
                },
            },
            paragraphes = {
                "Il fait nuit {lieu.dans}. Tout le monde dort… sauf {heros.nom}.",
                "{^heros.nom}, {heros.un} {heros.detail}, garde les yeux grands ouverts. Le noir, ça lui fait un peu peur.",
                "{^heros|Il|Elle} appelle tout doucement : « {^compagnon.nom}, tu dors ? »",
                "« Pas encore », répond {compagnon.nom} en bâillant. « Qu'est-ce qui se passe ? »",
                "« J'ai peur. {ombres#1.peur} »",
                "{^compagnon.nom} prend sa petite lanterne et regarde. « Mais non, n'aie pas peur. {ombres#1.vrai} »",
                "{^heros.nom} sursaute encore : « {ombres#2.peur} » {^compagnon.nom} lève sa lanterne. « Regarde bien. {ombres#2.vrai} »",
                "« Et ça ? {ombres#3.peur} » {^compagnon.nom} sourit. « {ombres#3.vrai} »",
                "{^heros.nom} sourit à son tour. « Alors la nuit, c'est comme le jour, mais avec la lumière éteinte ? » « Exactement, dit {compagnon.nom}. Le noir, c'est juste le monde qui fait dodo. »",
                "{^heros.nom} se blottit contre {compagnon.nom}. Tout est calme. Tout est doux. Et cette fois, {heros|il|elle} s'endort avec un grand sourire.",
            },
        },
        {
            id = "averse",
            titre = { "La grande averse", "{heros.nom} et l'arc-en-ciel" },
            age_min = 3, age_max = 5, themes = { "amitie", "nature" },
            choix = { jeux = { "à saute-mouton", "à la marelle", "au ballon", "à chat perché", "à la ronde" } },
            paragraphes = {
                "Il fait beau {lieu.dans}. {^heros.nom} et {compagnon.nom} jouent {jeux}.",
                "Soudain, un gros nuage gris arrive. Ploc. Ploc, ploc. Ploc, ploc, ploc ! Il pleut !",
                "« Vite, à l'abri ! » crie {compagnon.nom}. {^duo|Ils|Elles} courent se cacher {lieu.cachette}.",
                "La pluie tombe, tombe, tombe. {^heros.nom} est un peu triste : « Oh non, on ne peut plus jouer… »",
                "Mais {compagnon.nom} tend l'oreille. « Écoute ! La pluie fait de la musique. » Sur les feuilles, ça fait plic. Sur les cailloux, ça fait ploc. Et dans les flaques, ça fait splash !",
                "{^heros.nom} écoute, puis se met à chanter avec la pluie : « Plic, ploc, splash ! Plic, ploc, splash ! » {^compagnon.nom} tape du pied en rythme. Quel joli concert !",
                "Petit à petit, la pluie s'arrête. Le soleil revient. Et dans le ciel, que {duo|voient-ils|voient-elles} ?",
                "Un immense arc-en-ciel ! Rouge, orange, jaune, vert, bleu, violet. {^heros.nom} ouvre de grands yeux : « C'est la pluie et le soleil qui ont fait ça ensemble ? »",
                "« Oui, dit {compagnon.nom}. Comme nous deux : ensemble, on fait de belles choses. »",
                "Et {heros.nom} saute dans la plus grosse flaque. SPLASH ! {^duo|Ils|Elles} rient si fort que même l'arc-en-ciel a l'air de sourire.",
            },
        },
        {
            id = "cadeau",
            titre = { "Un cadeau pour {compagnon.nom}", "La couronne surprise" },
            age_min = 3, age_max = 5, themes = { "amitie", "partage" },
            choix = { cadeaux = { "une plume toute légère", "une jolie feuille en forme de cœur", "un caillou tout doux", "une petite fleur bleue", "un brin de laine rouge" } },
            paragraphes = {
                "Demain, {compagnon.nom} fête son anniversaire.",
                "{^heros.nom} voudrait lui offrir un cadeau. Mais {heros|il|elle} n'a pas d'argent, et il n'y a pas de magasin {lieu.dans}.",
                "Alors {heros.nom} part se promener pour trouver une idée. {^heros|Il|Elle} ramasse {lieu.tresor}, puis {cadeaux#1}, puis {cadeaux#2}.",
                "De retour dans {heros.maison}, {heros.nom} se met au travail. {^heros|Il|Elle} colle, {heros|il|elle} attache, {heros|il|elle} arrange… Et voilà une magnifique couronne !",
                "Le lendemain, {heros.nom} offre la couronne à {compagnon.nom}. « Joyeux anniversaire ! C'est moi qui l'ai fabriquée, avec des trésors {lieu.de}. »",
                "{^compagnon.nom} pose la couronne sur sa tête. Elle est un peu de travers, mais {compagnon|il|elle} la trouve parfaite.",
                "« C'est le plus beau cadeau du monde, parce que tu l'as fait rien que pour moi ! »",
                "Et toute la journée, {compagnon.nom} se promène avec sa couronne, {compagnon|fier comme un roi|fière comme une reine}.",
            },
        },
        {
            id = "couleurs",
            titre = { "{heros.nom} et les couleurs" },
            age_min = 2, age_max = 3, themes = { "apprendre" },
            choix = {
                couleurs = {
                    { c = "rouge", un = "une fraise", salut = "Bonjour, la fraise rouge !" },
                    { c = "jaune", un = "un poussin", salut = "Bonjour, le poussin jaune !" },
                    { c = "vert", un = "une grenouille", salut = "Bonjour, la grenouille verte !" },
                    { c = "bleu", un = "un papillon", salut = "Bonjour, le papillon bleu !" },
                    { c = "orange", un = "une carotte", salut = "Bonjour, la carotte orange !" },
                    { c = "blanc", un = "un mouton", salut = "Bonjour, le mouton blanc !" },
                    { c = "rose", un = "un petit cochon", salut = "Bonjour, le petit cochon rose !" },
                    { c = "violet", un = "une prune", salut = "Bonjour, la prune violette !" },
                },
            },
            paragraphes = {
                "{^heros.nom} se promène {lieu.dans}. {^heros|Il|Elle} ouvre grand les yeux, car aujourd'hui, {heros|il|elle} cherche des couleurs.",
                "Qu'est-ce qui est {couleurs#1.c} ? Regarde bien… C'est {couleurs#1.un} ! « {couleurs#1.salut} » dit {heros.nom}.",
                "Qu'est-ce qui est {couleurs#2.c} ? Regarde bien… C'est {couleurs#2.un} ! « {couleurs#2.salut} » dit {heros.nom}.",
                "Qu'est-ce qui est {couleurs#3.c} ? Regarde bien… C'est {couleurs#3.un} ! « {couleurs#3.salut} » dit {heros.nom}.",
                "Qu'est-ce qui est {couleurs#4.c} ? Regarde bien… C'est {couleurs#4.un} ! « {couleurs#4.salut} » dit {heros.nom}.",
                "Que de couleurs ! {^heros.nom} est {heros|fatigué|fatiguée}. {^heros|Il|Elle} rentre dans {heros.maison} et ferme les yeux. Dans le noir, {heros|il|elle} voit encore toutes les couleurs, comme un arc-en-ciel qui dit bonne nuit.",
                "Et toi, {enfant}, quelle est ta couleur préférée ?",
            },
        },
        {
            id = "cris",
            titre = { "Qui fait ce bruit ?", "{heros.nom} écoute les animaux" },
            age_min = 2, age_max = 3, themes = { "apprendre", "animaux" },
            choix = {
                animaux = {
                    { cri = "meuh, meuh", qui = "la vache" },
                    { cri = "coin-coin", qui = "le canard" },
                    { cri = "miaou", qui = "le chat" },
                    { cri = "bêê, bêê", qui = "le mouton" },
                    { cri = "ouaf, ouaf", qui = "le chien" },
                    { cri = "cot-cot-codet", qui = "la poule" },
                    { cri = "groin-groin", qui = "le cochon" },
                    { cri = "hi-han", qui = "l'âne" },
                    { cri = "croâ, croâ", qui = "la grenouille" },
                },
            },
            paragraphes = {
                "{^heros.nom} se promène {lieu.dans}. Chut… {^heros|Il|Elle} entend des bruits.",
                "Qui fait « {animaux#1.cri} » ? C'est {animaux#1.qui} !",
                "Qui fait « {animaux#2.cri} » ? C'est {animaux#2.qui} !",
                "Qui fait « {animaux#3.cri} » ? C'est {animaux#3.qui} !",
                "Qui fait « {animaux#4.cri} » ? C'est {animaux#4.qui} !",
                "Qui fait « {animaux#5.cri} » ? C'est {animaux#5.qui} !",
                "Et qui fait « bonne nuit, {enfant} », tout doucement ? C'est moi, qui te raconte cette histoire !",
            },
        },
        {
            id = "voyage",
            titre = { "{heros.nom} part en voyage", "Le grand voyage" },
            age_min = 4, age_max = 5, themes = { "aventure", "amitie" },
            choix = {
                transports = {
                    "D'abord, {heros.nom} grimpe sur le dos d'une gentille tortue. Elle avance tout doucement, mais elle connaît le chemin.",
                    "D'abord, {heros.nom} monte dans une petite barque. Plouf, plouf, font les rames sur l'eau.",
                    "D'abord, un grand oiseau blanc prend {heros.nom} sur son dos, et hop, ils s'envolent au-dessus des arbres !",
                    "D'abord, {heros.nom} saute dans le wagon d'un petit train. Tchou, tchou ! Le train file à travers les champs.",
                    "D'abord, une grosse montgolfière rouge passe par là. {^heros.nom} monte dans la nacelle et s'envole tout là-haut.",
                },
                suites = {
                    "Ensuite, {heros|il|elle} marche longtemps, longtemps, en chantant pour se donner du courage.",
                    "Ensuite, {heros|il|elle} traverse un petit pont de bois qui fait cric, crac sous ses pas.",
                    "Ensuite, {heros|il|elle} suit un papillon qui semble connaître le chemin.",
                },
            },
            paragraphes = {
                "{^heros.nom}, {heros.un} {heros.detail}, rêve depuis longtemps de découvrir {lieu.nom}. On raconte que c'est un endroit {lieu.detail}.",
                "Un matin, {heros|il|elle} prépare son sac : {heros.gouter}, une gourde d'eau fraîche et un chapeau pour le soleil. « En route ! »",
                "Le chemin est long, alors {heros.nom} voyage de toutes les façons.",
                "{transports}",
                "{suites}",
                "Enfin, {heros.nom} arrive {lieu.dans}. Comme c'est beau ! Tout autour, {lieu.son}.",
                "Là, {heros|il|elle} rencontre {compagnon.nom}, {compagnon.un} {compagnon.detail}. « Bienvenue ! Viens, je vais te montrer mon endroit préféré. »",
                "{^compagnon.nom} emmène {heros.nom} {lieu.cachette}. Là, il y a {lieu.tresor}. « C'est pour toi, pour que tu te souviennes de moi. »",
                "{^duo|Ils|Elles} jouent tout l'après-midi. Puis {heros.nom} partage son goûter avec {compagnon|son nouvel ami|sa nouvelle amie}.",
                "Le soir, {heros.nom} rentre chez {heros|lui, fatigué mais tellement content|elle, fatiguée mais tellement contente}. {^heros|Il|Elle} pose son trésor près de son lit.",
                "Et cette nuit-là, {heros|il|elle} rêve de son voyage. Et {compagnon.nom} est dans tous ses rêves.",
            },
        },
    },
}
